### ISSUE TITLE
Error Handling on Login

### ISSUE THREAD

**Issue by ttalhouk** [shaun-sweet/portal-project#22]
If error occurs we only are logging it to the console.  We need to add error messages on the form to help the user determine what is happening or redirect as needed.

**Comment by ttalhouk** [comment]
Added some error handling for auth errors in [PR](https://github.com/shaun-sweet/portal-project/pull/21).  This will give the user a message and highlight the appropriate field base on error with the email or the password.  Also added a notification div above if user closes the auth popup without authenticating.  More errors can be added to the handle error function as needed.

**Comment by shaun-sweet** [comment]
this was merged earlier today!

**Comment by shaun-sweet** [comment]
https://github.com/shaun-sweet/portal-project/pull/21
